# Generated by Django 5.2.7 on 2025-11-08 19:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Абонемент: ')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
                ('duration_days', models.IntegerField(default=30, verbose_name='Тривалість абонемента:')),
                ('visit_count', models.IntegerField(default=0, verbose_name='К-сть візитів')),
            ],
            options={
                'verbose_name': ' Тип абонемета',
                'verbose_name_plural': 'Тип абонементів',
            },
        ),
        migrations.CreateModel(
            name='ClientAbonement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата покупки')),
                ('start_date', models.DateField(verbose_name='Дата початку')),
                ('end_date', models.DateField(verbose_name='Дата закінчення')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
                ('visits_left', models.IntegerField(default=0, verbose_name='Залишилось візитів')),
                ('abonement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abonements.abonements', verbose_name='Тип абонемета')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Клієнт')),
            ],
            options={
                'verbose_name': ' Абонемент клієнта ',
                'verbose_name_plural': 'Всі абонементи',
            },
        ),
    ]
