# Generated by Django 4.2 on 2025-12-07 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0002_trainer_price'),
        ('abonements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientabonement',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainers.trainer', verbose_name='Тренер'),
        ),
    ]
