# Generated by Django 4.2 on 2025-12-09 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonements', '0002_clientabonement_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientabonement',
            name='method_payment',
            field=models.CharField(choices=[('cash', 'Готівка'), ('card', 'Карта')], default='card', max_length=10, verbose_name='Спосіб оплати'),
        ),
    ]
