# Generated by Django 4.2 on 2025-12-10 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_balance'),
        ('abonements', '0003_clientabonement_method_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Товар ')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
                ('quantity', models.IntegerField(default=0, verbose_name='Залишок товару')),
            ],
            options={
                'verbose_name': ' Товар ',
                'verbose_name_plural': 'Кількість товару',
            },
        ),
        migrations.CreateModel(
            name='ProductSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата покупки: ')),
                ('amount', models.IntegerField(default=0, verbose_name='Кількість')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
                ('method_payment', models.CharField(choices=[('cash', 'Готівка'), ('card', 'Карта'), ('balance', 'Баланс')], default='card', max_length=10, verbose_name='Спосіб оплати')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Клієнт')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='abonements.product', verbose_name='Товар ')),
            ],
        ),
    ]
