# Generated by Django 4.2 on 2025-12-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonements', '0004_product_productsale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsale',
            name='method_payment',
            field=models.CharField(choices=[('cash', 'Готівка'), ('card', 'Карта'), ('no_paid', 'НЕ оплачено!')], default='card', max_length=10, verbose_name='Спосіб оплати'),
        ),
    ]
