# Generated by Django 4.2 on 2025-12-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonements', '0005_alter_productsale_method_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsale',
            name='date',
            field=models.DateTimeField(verbose_name='Дата покупки: '),
        ),
    ]
