# Generated by Django 4.2 on 2025-12-12 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_remove_client_balance'),
        ('abonements', '0006_alter_productsale_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsale',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Клієнт'),
        ),
    ]
