# Generated by Django 5.2.7 on 2025-11-08 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255, verbose_name=" Ім'я тренера: ")),
                ('lastname', models.CharField(max_length=255, verbose_name=' Прізвище тренера:')),
                ('phone', models.CharField(max_length=12, unique=True, verbose_name='Телефон:')),
            ],
            options={
                'verbose_name': 'Тренер',
                'verbose_name_plural': 'Тренери',
            },
        ),
    ]
