# Generated by Django 4.2 on 2025-12-12 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='balance',
        ),
    ]
