# Generated by Django 4.2 on 2025-11-10 18:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('abonements', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Час візиту')),
                ('abonements', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='abonements.clientabonement', verbose_name='Абонемент')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Клієнт')),
            ],
            options={
                'verbose_name': ' Відвідування ',
                'verbose_name_plural': 'Відвідування',
                'ordering': ['-check_in_time'],
            },
        ),
    ]
